### ISSUE TITLE
Doesn't work for server-side rendered apps

### ISSUE THREAD

**Issue by trezy** [perrin4869/i18next-fetch-backend#1]
I'm building an application using [Next.js](https://github.com/zeit/next.js/). It provides both server-side and client-side rendering. Unfortunately, including [i18next-xhr-backend](https://github.com/i18next/i18next-xhr-backend) doesn't work server-side because we don't have access to `XMLHttpRequest`, and neither does i18next-fetch-backend because we don't have access to `fetch`.

However, [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch) could solve this issue by providing a `fetch` shim in a Node environment, or allowing passthrough to the native `fetch` function on the client-side. I'll be working on this tonight and making a PR, but I wanted to give you a heads up in case you had any qualms with this approach. ;-)

**Comment by perrin4869** [comment]
Sure, being able to specify a custom fetch function sounds like a great idea :D
PRs are welcome!

**Comment by 0xsven** [comment]
Same same. Doing next.js. Any chance this is being merged soon?

**Comment by perrin4869** [comment]
hm... I'm not at all familiar with `next.js` but bringing in a correct implementation of `fetch` should be done outside of this library. At the most, I could accept a PR that adds the option for a custom implementation of `fetch`, but probably a polyfill will work best. Is there a reason you can't polyfill `fetch` within `next.js`?

**Comment by trezy** [comment]
We can polyfill fetch in Next, but due to the module system that doesn't carry over to libraries. I.E. importing isomorphic-fetch for Next doesn't monkeypatch fetch for everything in Node. It needs to be imported in every instance where it's needed.

**Comment by perrin4869** [comment]
Hm... wouldn't it be fair to say that a solution to this problem should come from the `next.js` side then?
I could try to add an option to provide a custom implementation of `fetch`, maybe during the weekend. I would highly appreciate a PR for that.
But I really dislike the idea of forcing `isomorphic-fetch` upon everyone using this library

**Comment by trezy** [comment]
Well, the way we solve it with `next.js` is by importing `isomorphic-fetch`. Because `next.js` does both client-side *and* server-side rendering of Javascript applications, you need to use `isomorphic-fetch` if you want to use the `fetch` API at all.

I can see why you wouldn't want to jam another library into this one and providing an API for defining a custom `fetch` implementation may be enough to solve the problem. However, implementing `isomorphic-fetch` inside of `i18next-fetch-backend` doesn't make a substantial size difference, but it does make the library more versatile. Admittedly, I don't need to use use `i18next-fetch-backend`. If I'm worried about having to support browsers that don't support `fetch`, I could use `i18next-xhr-backend` instead. However, I like the `fetch` API. It's far simpler than XHR, so if I can use it, I will. I also pull in the `isomorphic-fetch` polyfill anytime I want to use it so that I don't need to worry about where my code is being run, I'll always have a working implementation of `fetch`.

Ideologically, I'm with you on not including `isomorphic-fetch`. Pragmatically, though, I don't see the cons of it's inclusion outweighing the pros.

**Comment by perrin4869** [comment]
Well, the pragmatic reason not to do it is that this is the exact kind of thing that could lead to weird, unwanted, unexpected results in other people's code who aren't expecting `isomorphic-fetch` to be there...

**Comment by perrin4869** [comment]
Will close for now. In `v2.0.0` you can pass in a custom `fetch` function as an option

**Comment by layerdev** [comment]
Still not working
