### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by fcastilloec** [perrin4869/i18next-fetch-backend#15]
I've noticed that version `1.0.0` has been released but there's nowhere I can read about the changes.
Could you provide a changelog, either as a separate `.md` file, or as part of the releases page in Github?

**Comment by perrin4869** [comment]
Sorry, should get into the habit of doing that everytime ><;;
Done [here](https://github.com/perrin4869/i18next-fetch-backend/releases/tag/v1.0.0)
