### ISSUE TITLE
Doesn't work in Internet Explorer 10 or older.

### ISSUE THREAD

**Issue by tnlogy** [perrin4869/i18next-fetch-backend#7]
Since IE have some problems with inheriting static properties on subclasses
https://github.com/babel/babel/issues/116

You need to add:
FetchBackend.type = 'backend'

modules.backend will otherwise be undefined when using IE10 or older.

**Comment by perrin4869** [comment]
Hm... I think that `IE <= 10` support at this point is your own responsibility, but thanks for catching this! I'll add a note in the `README.md` with the `IE <= 10` fix and the solution you provided :)

**Comment by perrin4869** [comment]
Addressed this issue in https://github.com/perrin4869/i18next-fetch-backend/commit/0bb45e5d39e446c44392641646136473cc91d6ea, thanks!
